<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_thumb_14')->toHtml(); ?>
	</div>
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home5')->toHtml(); ?>
	</div>
	
</div>
<div class="deals_product">
	<div class="container">
		<div class="hot-deal">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Superdeals\Block\ProductByCat')->setTemplate('Rokanthemes_Superdeals::category.phtml')->toHtml();?>
		</div>
	</div>
</div>
<div class="block_notification">
<div class="container">
<marquee direction="" data-role="notification-marquee">
<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('notification_home5')->toHtml(); ?>
</marquee>
</div>
</div>
<div class="group_h14">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6">
				<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>
			</div>
			<div class="col-xs-12 col-sm-6">
				<?php echo $block->getLayout()->createBlock('Rokanthemes\Toprate\Block\Toprate')->setTemplate('Rokanthemes_Toprate::toprate.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>
<div class="the_blog">
	<div class="container">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
	</div>
</div>
<div class="container">
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
</div>

<script type="text/x-magento-init">
{
    ".block_notification [data-role=\"notification-marquee\"]": {
        "js/notification-marquee": {}
    },
    ".common-tab-system-fixed": {
        "js/top-home-tabs": {}
    }
}
</script>