<div class="top-home-content">
	<div class="container">
		<div class="banner-slider banner-slider4">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage4slider')->toHtml(); ?>
		</div>
		<div class="banner_mid_4">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid_home4')->toHtml(); ?>
		</div>
	</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
		<div class="hot-deal">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Superdeals\Block\ProductByCat')->setTemplate('Rokanthemes_Superdeals::category.phtml')->toHtml();?>
		</div>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home4')->toHtml(); ?>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category2_home4')->toHtml(); ?>
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid_home1')->toHtml(); ?>
		</div>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category3_home4')->toHtml(); ?>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category4_home4')->toHtml(); ?>
		<div class="the_blog">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Testimonials\Block\Testimonials')->setTemplate('Rokanthemes_Testimonials::slider.phtml')->toHtml();?>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand_section')->toHtml(); ?>
	</div>
</div>
<script type="text/x-magento-init">
{
	".common-tab-system-fixed": {
		"js/top-home-tabs": {}
	}
}
</script>