<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="item-post-full post-holder-<?php echo (int)$_post->getId() ?> col-sm-6 col-xs-12">
	<div class="blog-post-thumb">
		
		<div class="zoom-image-thumb">
			<a href="<?php echo $block->escapeUrl($_post->getPostUrl()) ?>">
				<img src="<?php echo $block->escapeUrl($this->getMediaFolder().$_post->getDetailimage()) ?>" alt="<?php echo $block->escapeHtmlAttr($_post->getTitle()) ?>" loading="lazy" />
			</a>
		</div>		
	</div>
	<div class="blog-post-info">
		<h3 class="post-title"><a title="<?php echo $block->escapeHtmlAttr($_post->getTitle()) ?>" href="<?php echo $block->escapeUrl($_postUrl) ?>"> <?php echo $_postName; ?></a></h3>
		<div class="post-info-extra"><?php echo $block->escapeHtml(__('Post Date:')) ?>
			<div class="post-date"><strong><?php echo date('d', strtotime($_post->getPublishTime())); ?></strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span></div>
			<!-- <div class="post-format"><i class="fa fa-picture-o"></i></div> -->
		</div>
		<div class="desc">
			<?php /* @noEscape */ echo $_post->getShortContent() ?>
		</div>
		<div class="post-info-bottom clearfix">
			<a href="<?php echo $block->escapeUrl($_post->getPostUrl()) ?>" class="post-readmore pull-left"><?php echo $block->escapeHtml(__('Read More'));?></a>
			<div class="post-tags-info pull-right">
				<?php /* @noEscape */ echo $this->getInfoHtml() ?>
			</div>
		</div>
	</div>
</div>