<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
if($banners = $block->getBannerCollection()):
	$slider = $block->getSlider();
	$sliderId = $block->getSliderId(); 
?>
<div class="wrapper_slider hidden-xs slider_<?php echo $sliderId; ?>">
	<div class="owl">
		<?php foreach($banners as $banner){ if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImage());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
				<div class="text-banner">
					<?php if($text = $banner->getSlideText()){
						echo $block->getContentText($text); 
					}
					?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
<div class="wrapper_slider visible-xs slider_<?php echo $sliderId; ?>_mobile">
	<div class="owl">
		<?php foreach($banners as $banner){  if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImageMobile());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
				<div class="text-banner">
					<?php if($text = $banner->getSlideText()){
						echo $block->getContentText($text); 
					}
					?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
<script type="text/x-magento-init">
    {
        ".wrapper_slider": {
            "Rokanthemes_SlideBanner/js/slider": {
                "sliderId": "<?php echo $sliderId; ?>",
                "sliderSettings": {
                    "lazyLoad": true,
                    <?php foreach($slider->getSliderSetting() as $key=>$value):
                        if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
                            $value = ($value == 1) ? true : false;
                        }
                        echo '"' . $key . '": ' . json_encode($value) . ',';
                    endforeach; ?>
                },
                "sliderMobileSettings": {
                    "lazyLoad": true,
                    <?php foreach($slider->getSliderSetting() as $key=>$value):
                        if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
                            $value = ($value == 1) ? true : false;
                        }
                        echo '"' . $key . '": ' . json_encode($value) . ',';
                    endforeach; ?>
                }
            }
        }
    }
</script>
<?php endif; ?>
