<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Search\Block\Index\Base $block */

/** @var \Aheadworks\Blog\Block\Post $postBlock */
$postBlock = $this->getLayout()->createBlock('Aheadworks\Blog\Block\Post');
?>
<div class="mst-search__index mst-search__index-aheadworks-blog-post">
    <div class="blog-posts">
        <?php /** @var \Aheadworks\Blog\Model\Post $post */ ?>
        <?php foreach ($block->getCollection() as $post): ?>
            <div class="post-item">
                <h3 class="post-title">
                    <a href="<?php /* @noEscape */ echo $block->escapeXssInUrl($postBlock->getPostUrl($post)) ?>"><?= $block->escapeHtml($post->getTitle()) ?></a>
                </h3>
                <div class="blog-post-content">
                    <?= $block->truncate(
                            $block->stripTags(
                                /* @noEscape */ $postBlock->getContent($post)
                            )
                    ) ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
