<?php

use Mirasvit\Core\Service\CspService;

/** @var Mirasvit\Search\Block\Adminhtml\Menu $block */

$nonce = CspService::getNonce();
?>
<script<?php if ($nonce): ?> nonce="<?= $block->escapeHtml($nonce) ?>"<?php endif; ?>>
    require(['jquery'], function ($) {
    	$(document).ready(function($){
    		setTimeout(function() {
				if ($('#search_engine_engine').length > 0 && $('#search_engine_engine option:selected').val() == 'sphinx' &&
						$('#search_engine_restart').length == 0 && $('#search_engine_clear').length == 0) {

			        $('#row_search_engine_config').show();
			        $('#search_engine_config').show();
			    }
			}, 1000);
    	});
    });
</script>
