<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postNameStripped = $block->stripTags($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo (int)$_post->getId() ?>">
		<div class="post-images">
			<a href="<?php echo $block->escapeUrl($_post->getPostUrl()) ?>">
                <img src="<?php echo $block->escapeUrl($this->getMediaFolder().$_post->getDetailimage()) ?>" alt="<?php echo $block->escapeHtmlAttr($_post->getTitle()) ?>" loading="lazy" />
			</a> 
			
		</div> 
       
        <div class="post-content">
            
             <h3 class="post-title"><a title="<?php echo $block->escapeHtmlAttr($_post->getTitle()) ?>" href="<?php echo $block->escapeUrl($_postUrl) ?>"><?php echo $_postNameStripped; ?></a>
             </h3>
             <div class="post-info-extra"><?php echo $block->escapeHtml(__('Post Date:')) ?>
                <div class="post-date"><strong><?php echo date('d', strtotime($_post->getPublishTime())); ?></strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span></div>
                <!-- <div class="post-format"><i class="fa fa-picture-o"></i></div> -->
            </div>
            <div class="post-description">
                <?php /* @noEscape */ echo $block->getContent() ?>
                <div class="clear"></div>
            </div>
        </div>
         <div class="post-header clearfix">

            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $block->escapeUrl($_postUrl) ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div> 
        </div>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>