<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $storeName = $block->getThemeName() ?: $block->getLogoAlt(); ?>
<div class="logo">
<?php if (!$block->isHomePage()): ?>
    <a href="<?= $escaper->escapeUrl($block->getUrl('')) ?>" title="<?= $escaper->escapeHtmlAttr($storeName) ?>">
<?php endif ?>
        <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
             alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
             <?php if ($block->getLogoWidth()): ?>width="<?= $escaper->escapeHtmlAttr($block->getLogoWidth()) ?>"<?php endif ?>
             <?php if ($block->getLogoHeight()): ?>height="<?= $escaper->escapeHtmlAttr($block->getLogoHeight()) ?>"<?php endif ?>
             loading="eager"
        />
<?php if (!$block->isHomePage()): ?>
    </a>
<?php endif ?>
