<div class="top-home-content">
		<div class="banner-slider banner-slider2">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage6slider')->toHtml(); ?>
		</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_mid_home6')->toHtml(); ?>
		</div>
		<div class="new_product">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
		</div>
	</div>
</div>
<div class="onsale_product">
	<div class="container">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?>
	</div>
</div>
<div class="block_notification">
<div class="container">
<marquee direction="" data-role="notification-marquee">
<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('notification_home6')->toHtml(); ?>
</marquee>
</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_home6')->toHtml(); ?>
		<div class="the_blog">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
{
    ".block_notification [data-role=\"notification-marquee\"]": {
        "js/notification-marquee": {}
    },
    ".common-tab-system-fixed": {
        "js/top-home-tabs": {}
    }
}
</script>