<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="logo">
<?php if (!$block->isHomePage()):?>
    <a href="<?php echo $block->escapeUrl($block->getUrl('')); ?>" title="<?php echo $block->escapeHtmlAttr($storeName) ?>">
<?php endif ?>
	<img src="<?php echo $block->escapeUrl($block->getLogoSrc()) ?>"
		 alt="<?php echo $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
		 <?php echo $block->getLogoWidth() ? 'width="' . (int)$block->getLogoWidth() . '"' : '' ?>
		 <?php echo $block->getLogoHeight() ? 'height="' . (int)$block->getLogoHeight() . '"' : '' ?>
	/>
<?php if (!$block->isHomePage()):?>
    </a>
<?php endif?>
</div>
